spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003171

server:
  port: ${eureka.port}

logging:
  file: /opt/logs/100003171/apollo-configservice.log
