apollo:
  bootstrap:
    enabled: true
    # will inject 'application' and 'TEST1.apollo' namespaces in bootstrap phase
    namespaces: application,redis
spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile}
  session:
    namespace: ApolloPortal
    maxInactiveIntervalInSeconds: 7200
  jpa:
    properties:
      hibernate:
        query:
          plan_cache_max_size: 192 # limit query plan cache max size

server:
  port: 8070
  compression:
    enabled: true
  tomcat:
    use-relative-redirects: true

logging:
  file: /opt/logs/100003173/apollo-portal.log

management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP



unitop:
  sso:
    server: ${sso.url}
    logout:
      path: /logout
    redis:
      expire:
        minite: 480
    ignorePattern: /jobAPI,/router,/sessionTimeout.jsp,/test.html,/static,/assets,/login,/doLogin,/**/app/**,/health
